title: Sebastián Vallejo Vera
url: "https://www.svallejovera.com"
baseurl: "https://www.svallejovera.com"
repository: svallejovera/svallejovera.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page based on a design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "vallejo cv.pdf"
 - name: "Contact"
   link: "contact"
 - name: "iLCSS"
   link: "https://ilcss.umd.edu/"
